baseURL = "https://www.flokoe.de/"
languageCode = "en"
title = "flokoe"
enableEmoji = false
disableKinds = ["taxonomy", "term"]
enableGitInfo = true
timeZone = "Europe/Berlin"
enableRobotsTXT = true
theme = "simple"

[build]
  writeStats = true

[minify]
disableSVG = true

[markup.highlight]
  style = "dracula"

[markup.goldmark.parser.attribute]
  block = true

[menu]
[[menu.social]]
  identifier = 'github'
  pre = 'GitHub'
  url = 'https://github.com/flokoe/'
  weight = 10

[[menu.social]]
  identifier = 'twitter'
  pre = 'Twitter'
  url = 'https://twitter.com/flokoe_'
  weight = 20

[[menu.social]]
  identifier = 'mail'
  pre = 'Email'
  url = 'mailto:hi@flokoe.de'
  weight = 30
