baseURL = "https://hellodevops.blog/"
languageCode = "en"
title = "Hello DevOps"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.highlight]
  style = "dracula"
  lineNos = true

[markup.goldmark.parser.attribute]
  block = true
