[build]
  publish = "public/"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.87.0"
  NODE_VERSION = "16"

[[redirects]]
  from = "https://hellodevops.netlify.app/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://hellodevops.netlify.app/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hellodevops.blog/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true
