[build]
  publish = "public/"
  command = "hugo --minify --logLevel info"

[build.environment]
  HUGO_VERSION = "0.136.5"
  NODE_VERSION = "20"

[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; img-src 'self'; script-src 'self' https://plausible.io 'sha256-DxdO0KMifr4qBxX++GTv0w7cNu8FeArRvitEZf1FSrE=' 'sha256-bfloDFhW9eAYHv7CGM+kIiD7H2F+b/hGF5Wj8LOnLyo='; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; connect-src 'self' https://plausible.io"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    #Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/.well-known/nostr.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "http://hellodevops.netlify.app/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://hellodevops.netlify.app/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://hellodevops.blog/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://hellodevops.blog/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hellodevops.blog/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.hellodevops.blog/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://flokoe.de/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://flokoe.de/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.flokoe.de/*"
  to = "https://www.flokoe.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/buymeabeer*"
  to = "/support/"
  status = 301
  force = true
