[build]
  publish = "public/"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.87.0"
  NODE_VERSION = "16"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; img-src 'self'; script-src 'self' 'https://plausible.io' 'sha256-MGYxNzRlZDBhMzIyN2ViZTJhMDcxNWZlZjg2NGVmZDMwZWRjMzZlZjA1NzgwYWQxYmUyYjQ0NjVmZDQ1NGFiMQ==' 'sha256-MzI1ZmE3YTE4YWM3YzlkODgyZTUyOWM4OGM4NjhkYTcyYjI4MGYwNWNlODgzZDg2ZjY0Nzk4MDg3YzAxNjA4MA=='; style-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; connect-src 'self' https://plausible.io"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
  from = "https://hellodevops.netlify.app/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://hellodevops.netlify.app/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://hellodevops.blog/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hellodevops.blog/*"
  to = "https://www.hellodevops.blog/:splat"
  status = 301
  force = true
