name: Netlify Build
'on':
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * 1'
jobs:
  build:
    name: Trigger Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send curl request
        env:
          NETLIFY_WEBHOOK: ${{ secrets.NETLIFY_WEBHOOK }}
        run: curl -X POST -d {} "$NETLIFY_WEBHOOK"
